Update scraper.py
attempted fix of : 
```
C:\Users\Me\Desktop\ResumeLinguist\venv\Scripts\python.exe C:\Users\Me\Desktop\ResumeLinguist\scraper.py
C:\Users\Me\Desktop\ResumeLinguist\scraper.py:58: FutureWarning: The default value of regex will change from True to False in a future version.
  data["Location"] = data["Location"].astype(str).str.replace(r"[\(\[].*?[\)\]]", "").str.strip()
Data scraped and saved successfully.
Error: No job description texts found.
Traceback (most recent call last):
  File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 217, in <module>
    train_resume_model()
  File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 120, in train_resume_model
    data = pd.read_csv("usajobs_data_with_features.csv")
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\parsers\base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\pandas\io\common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'usajobs_data_with_features.csv'

Process finished with exit code 1

```